runtime: python38
entrypoint: gunicorn -b :$PORT main:app
handlers:
  - url: /js
    static_dir: api/static/js
  - url: /css
    static_dir: api/static/css
  - url: /img
    static_dir: api/static/img
  - url: /user/.*
    static_files: api/templates/index.html
    upload: api/templates/index.html
  - url: /login
    static_files: api/templates/index.html
    upload: api/templates/index.html
  - url: /register
    static_files: api/templates/index.html
    upload: api/templates/index.html
  - url: /.*
    script: auto
    secure: always

includes:
 - env_variables.yaml

  # - url: /.*
  #   secure: always
#   redirect_http_response_code: 301
#   script: auto